#!/bin/zsh

#------------------------------------------------------------------------------
# .zshenv - Zsh environment file, loaded always. (inspired by https://github.com/getantidote/zdotdir)
# 
# NOTE: .zshenv needs to live at ~/.zshenv, not in $ZDOTDIR!
#------------------------------------------------------------------------------

# Set ZDOTDIR if you want to re-home Zsh.
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export ZDOTDIR=${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath

# Set the list of directories that zsh searches for commands.
path=(
  $HOME/{,s}bin(N)
  $HOME/.local/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

# Environment variables that should be loaded for all shell types
export PATH="/Users/hank/.local/bin:$PATH"
export LANG=en_US.UTF-8  # Important for character encoding

